---
name: GoLangCI
on:
  workflow_call:
    secrets:
      bitbucketSSHKey:
        required: true
      sshKey:
        required: true
jobs:
  golangci-lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: |
            ${{ secrets.bitbucketSSHKey }}
            ${{ secrets.sshKey }}

      - name: Configure SSH access to bitbucket.org
        run: |
          git config --global --add url."ssh://git@bitbucket.org/".insteadOf "https://bitbucket.org/"

      - name: Configure SSH access to github.com
        run: |
          git config --global --add url."ssh://git@github.com/".insteadOf "https://github.com/"

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Linting
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --modules-download-mode=readonly --enable=gosec,misspell --timeout=5m0s ./...
          skip-go-installation: true

      - name: Unit testing
        run: go test -race -count=1 -cover -covermode=atomic ./...