---
name: GoLangCI
on:
  workflow_call:
    inputs:
      lintVersion:
        type: string
        default: latest
        required: false
      goVersion:
        type: string
        default: 1.22.x
        required: false
      skipTests:
        type: string
        default: false
        required: false
    secrets:
      bitbucketSSHKey:
        required: true
      sshKey:
        required: true

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  GOPRIVATE: "bitbucket.org/scanimal/*,github.com/Equineregister/*"
jobs:
  golangci-lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.bitbucketSSHKey }}
            ${{ secrets.sshKey }}

      - name: Configure SSH access to bitbucket.org
        run: |
          echo "bitbucket.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIazEu89wgQZ4bqs3d63QSMzYVa0MuJ2e2gKTKqu+UUO" >>${HOME}/.ssh/known_hosts
          git config --global --add url."ssh://git@bitbucket.org/".insteadOf "https://bitbucket.org/"

      - name: Configure SSH access to github.com
        run: |
          echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >>${HOME}/.ssh/known_hosts
          git config --global --add url."ssh://git@github.com/".insteadOf "https://github.com/"

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.goVersion }}

      - name: Clean Go module cache
        run: go clean -modcache

      - name: Linting
        uses: golangci/golangci-lint-action@v2
        with:
          version: ${{ inputs.lintVersion }}
          args: --modules-download-mode=readonly --enable=gosec,misspell --timeout=5m0s ./...
          skip-go-installation: true
