---
name: GoLangCI
on:
  workflow_call:
    secrets:
      bitbucketSSHKey:
        required: true
      sshKey:
        required: true
jobs:
  golangci-lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: |
            ${{ secrets.bitbucketSSHKey }}
            ${{ secrets.sshKey }}

      - name: Configure SSH access to bitbucket.org
        run: |
          echo "bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==" >>${HOME}/.ssh/known_hosts
          git config --global --add url."ssh://git@bitbucket.org/".insteadOf "https://bitbucket.org/"

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Linting
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --modules-download-mode=readonly --enable=gosec,misspell --timeout=5m0s ./...
          skip-go-installation: true

      - name: Unit testing
        run: go test -race -count=1 -cover -covermode=atomic ./...